---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true
  become_method:  sudo
  become_user: ubuntu 
  #  vars:
  #    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: install Apache
      package:
        name: 'apache2'
        state: present
